name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hadolint:
    uses: SkynetLabs/.github/workflows/dockerfile-lint.yml@master

  tests:
    uses: ./.github/workflows/tests.yml
